export const level1Data = [
  {
    a: '친구: 우리 조카 사진이에요. 귀엽죠?',
    av: 'Bạn: Đây là ảnh cháu tôi. Đáng yêu đúng không?',
    b: '__, 아기가 너무 귀여워요! 인형인 줄 알았네.',
    bv: '__, Em bé đáng yêu quá đi! Tớ cứ tưởng là búp bê cơ đấy.',
    ans: ['아이구!/아이고!'],
  },
  {
    a: '친구: 나 이번에 한국어 능력 시험(TOPIK) 6급 합격했어!',
    av: 'Bạn: Tớ vừa đỗ TOPIK cấp 6 rồi!',
    b: '__, 진짜 축하해!',
    bv: '__, Chúc mừng cậu nhé!',
    ans: ['대박!'],
  },
  {
    a: '친구: 2026년부터 시급이 10,300원으로 확정됐대!',
    av: 'Bạn: Nghe nói lương theo giờ năm 2026 được chốt là 10.300 won rồi đấy!',
    b: '__, 진짜? 드디어 만 원이 넘었네! 대박이다.',
    bv: '__, thật á? Cuối cùng cũng vượt qua mức 10 ngàn won rồi! Đỉnh thật sự.',
    ans: ['헐'],
  },
  {
    a: '내일 학교 축제에 EXO가 온대.',
    av: 'Bạn: Nghe nói mai  EXO đến lễ hội trường mình đấy.',
    b: '__, 대박, 무조건 가야겠네!',
    bv: '__, Tuyệt quá, nhất định phải đi thôi!',
    ans: ['진짜?'],
  },
  {
    a: '친구: 와! 저기 식당 앞에 줄 서 있는 것 좀 봐.',
    av: 'Bạn: Oa! Nhìn dòng người xếp hàng trước nhà hàng kia kìa.',
    b: '그러게. 줄이 __. 맛집인가 봐.',
    bv: 'Công nhận. Dài không __. Chắc là quán ngon rồi.',
    ans: ['장난 아니다'],
  },
  {
    a: '친구: 내가 콘서트 티켓 구매했어! ',
    av: 'Bạn: Tớ mua được vé Concert rồi!',
    b: '__, 대박이다!',
    bv: '__, Tuyệt quá!',
    ans: ['와'],
  },
  {
    a: '친구: 오늘 수업 취소됐어.',
    av: 'Bạn: Hôm nay được nghỉ học đấy',
    b: '__, 너무 좋아요!',
    bv: '__, Thích ghê!',
    ans: ['아, 진짜요?'],
  },
  {
    a: '친구: 지금 영화 볼까?',
    av: 'Bạn: Đi xem phim bây giờ không?',
    b: '좋아, __.',
    bv: 'Ok,  __.',
    ans: ['고고'],
  },
  {
    a: '친구: 이 카페 어때?',
    av: 'Bạn: Quán cà phê này sao?',
    b: '생각보다 __.',
    bv: '__ ha.',
    ans: ['나쁘지 않네'],
  },
  {
    a: '친구: 오늘 시험 있어.',
    av: 'Bạn: Hôm nay tớ có bài kiểm tra.',
    b: '__! 잘 보고 와!',
    bv: '__! Làm tốt nha!',
    ans: ['파이팅'],
  },
];

export const storyData = {
  ko: {
    story:
      '당신은 한국어 공부를 열심히 했습니다.<br>대학교에서 새로운 한국 친구를 만났어요.<br>친구가 기분이 좋아 보이네요!<br>긍정적인 반응으로 공감해 줍시다.',
    start: '친구에게 다가가기',
    correct: '정답입니다! 잘했어요.',
    wrong: '틀렸습니다! 다시 풀어보세요.',
    gameOverTitle: '게임 오버',
    gameOverDesc: '친구와 사이가 서먹서먹해졌습니다... 😢',
    restart: '다시 도전하기',
  },
  vn: {
    story:
      'Bạn đã chăm chỉ học tiếng Hàn.<br>Bạn gặp một người bạn Hàn Quốc mới tại trường đại học.<br>Bạn của bạn trông có vẻ đang rất vui!<br>Hãy đồng cảm bằng những phản ứng tích cực nhé.',
    start: 'Đến gần bạn của bạn',
    correct: 'Chính xác! Làm tốt lắm.',
    wrong: 'Sai rồi! Hãy thử lại nhé.',
    gameOverTitle: 'Trò chơi kết thúc',
    gameOverDesc: 'Mối quan hệ với bạn bè đã trở nên ngại ngùng... 😢',
    restart: 'Thử lại lần nữa',
  },
};

export const fillerPool = [
  '에이',
  '설마',
  '하아',
  '망했다',
  '젠장',
  '휴',
  '뭐야',
  '아니',
  '무슨',
  '뭘?',
  '어쩌라고?',
  '그래서?',
  '그만',
  '왜?',
  '미친',
  '뭐가?',
  '어떻게?',
  '구라치지마',
];
